### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by nksaunders** [christinahedges/contaminante#1]
This is **great**! I'm having fun playing around with this and seeing how it performs for different known systems. I have a few bugfixes and suggestions for this early version of the code:

- the line `lightkurve>=1.10` in `requirements.txt` did not recognize my lightkurve version (`1.10.dev`) as a compatible version and the install failed
- I'm guessing on [this line](https://github.com/christinahedges/contaminante/blob/446fc88ff43696c32ff9a1f02a96cb4ffa4d5391/contaminante/utils.py#L165) you mean to pass `mission` instead of `period` into `search()`
- it would be good to suppress the warning that's raised for `TESSCut` targets. It tries to search for a target pixel file which fails, producing the error message `No data found for target "TIC ######".` This is subtle but it confused me when I first got the warning.

I'm excited to use this more!

**Comment by christinahedges** [comment]
@nksaunders these are GREAT keep em coming, I'm working more on this now.
