### ISSUE TITLE
Incorrect package name in docs

### ISSUE THREAD

**Issue by danhey** [christinahedges/contaminante#2]
Hi Christina, this package is awesome! It looks like the pip name on the docs is incorrectly listed as `contaminate`, not `contaminante`.
<img width="503" alt="Screen Shot 2020-05-22 at 2 16 54 pm" src="https://user-images.githubusercontent.com/38233719/82630730-ead1b380-9c36-11ea-8eca-117ffa296094.png">

Cheers!

**Comment by christinahedges** [comment]
Hey Dan,

Thanks for this, what a silly mistake! My own fault for trying to follow astronomy naming games! ;)

Cheers!
